name: Update GOBL

on:
  repository_dispatch:
    types: [gobl-release]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Update GOBL dependency
        run: |
          go get github.com/invopop/gobl@${{ github.event.client_payload.version }}
          go mod tidy

      - name: Verify build
        run: go build ./...

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Update GOBL to ${{ github.event.client_payload.version }}"
          body: |
            Automated update triggered by a new GOBL release.

            **Version:** `${{ github.event.client_payload.version }}`
          branch: "deps/gobl-${{ github.event.client_payload.version }}"
          commit-message: "Update GOBL to ${{ github.event.client_payload.version }}"
